# Generated by Django 5.0.2 on 2024-03-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_booking_end_time_remove_booking_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='hrs',
            field=models.IntegerField(),
        ),
    ]
