# Generated by Django 5.0.2 on 2024-04-03 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_guide_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/img'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/img'),
        ),
    ]
