# Generated by Django 5.0.2 on 2024-03-05 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_user_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userType',
            field=models.CharField(choices=[('1', 'Guide'), ('2', 'User')], default='1', max_length=20),
        ),
    ]
